services:
    db:
        image: postgres:latest
        restart: always
        env_file:
            - env/database.env
        volumes:
            - postgres-volume:/var/lib/postgresql/data
        logging:
            driver: none

    watcher:
        deploy:
            restart_policy:
                condition: always
                delay: 1m
        build:
            context: ./
            dockerfile: watcher/Dockerfile
        env_file:
            - env/database.env
            - env/nearblocks.env
        depends_on:
            - db

    tester:  # for testing through `exec -it`
        restart: always
        build: .
        env_file:
            - env/database.env
        tty: true
        volumes:
            - ./:/test

volumes:
    postgres-volume:
